# The simulator puts out a huge amount of logs, limit what is saved
x-log-options:
  &log-options
  logging:
    options:
      max-size: "20m"
      max-file: "10"

services:
  acu-simulator:
    image: soaculib:latest
    <<: *log-options
    network_mode: "host"
    entrypoint: ["/usr/local/bin/python", "/app/soaculib/simulator/simulator_server.py"]
    init: true
