status_fields = {
    'Datasets.StatusSATPDetailed8100' : {
        'Time' : float,
        'Year' : int,
        'Azimuth mode' : str,
        'Azimuth current position' : float,
        'Azimuth current velocity' : float,
        'Elevation mode' : str,
        'Elevation current position' : float,
        'Elevation current velocity' : float,
        'Boresight mode' : str,
        'Boresight current position' : float,
        'Qty of free program track stack positions' : int,
        'Azimuth average position error' : float,
        'Azimuth peak position error' : float,
        'Elevation average position error' : float,
        'Elevation peak position error' : float,
        'Azimuth CCW limit: 2nd emergency' : bool,
        'Azimuth CCW limit: emergency' : bool,
        'Azimuth CCW limit: operating' : bool,
        'Azimuth CCW limit: pre-limit' : bool,
        'Azimuth CCW limit: operating (ACU software limit)' : bool,
        'Azimuth CCW limit: pre-limit (ACU software limit)' : bool,
        'Azimuth CW limit: pre-limit (ACU software limit)': bool,
        'Azimuth CW limit: operating (ACU software limit)' : bool,
        'Azimuth CW limit: pre-limit' : bool,
        'Azimuth CW limit: operating' : bool,
        'Azimuth CW limit: emergency' : bool,
        'Azimuth CW limit: 2nd emergency' : bool,
        'Elevation Down limit: extended emergency (co-moving shield off)' : bool,
        'Elevation Down limit: extended operating (co-moving shield off)' : bool,
        'Elevation Down limit: emergency' : bool,
        'Elevation Down limit: operating' : bool,
        'Elevation Down limit: pre-limit' : bool,
        'Elevation Down limit: operating (ACU software limit)' : bool,
        'Elevation Down limit: pre-limit (ACU software limit)' : bool,
        'Elevation Up limit: pre-limit (ACU software limit)' : bool,
        'Elevation Up limit: operating (ACU software limit)' : bool,
        'Elevation Up limit: pre-limit' : bool,
        'Elevation Up limit: operating' : bool,
        'Elevation Up limit: emergency' : bool,
        'Boresight CCW limit: emergency' : bool,
        'Boresight CCW limit: operating' : bool,
        'Boresight CCW limit: pre-limit' : bool,
        'Boresight CCW limit: operating (ACU software limit)' : bool,
        'Boresight CCW limit: pre-limit (ACU software limit)' : bool,
        'Boresight CW limit: pre-limit (ACU software limit)' : bool,
        'Boresight CW limit: operating (ACU software limit)' : bool,
        'Boresight CW limit: pre-limit' : bool,
        'Boresight CW limit: operating' : bool,
        'Boresight CW limit: emergency': bool,
        'Azimuth summary fault' : bool,
        'Azimuth motion error' : bool,
        'Azimuth motor 1 overtemperature' : bool,
        'Azimuth motor 2 overtemperature' : bool,
        'Azimuth overspeed' : bool,
        'Azimuth regeneration resistor 1 overtemperature' : bool,
        'Azimuth regeneration resistor 2 overtemperature' : bool,
        'Azimuth overcurrent motor 1' : bool,
        'Azimuth overcurrent motor 2' : bool,
        'Elevation summary fault' : bool,
        'Elevation motion error': bool,
        'Elevation motor 1 overtemp': bool,
        'Elevation overspeed': bool,
        'Elevation regeneration resistor 1 overtemperature': bool,
        'Elevation overcurrent motor 1': bool,
        'Boresight summary fault': bool,
        'Boresight motion error': bool,
        'Boresight motor 1 overtemperature': bool,
        'Boresight motor 2 overtemperature': bool,
        'Boresight overspeed': bool,
        'Boresight regeneration resistor 1 overtemperature': bool,
        'Boresight regeneration resistor 2 overtemperature': bool,
        'Boresight overcurrent motor 1': bool,
        'Boresight overcurrent motor 2': bool,
        'Azimuth oscillation warning': bool,
        'Elevation oscillation warning': bool,
        'Boresight oscillation warning': bool,
        'Azimuth servo failure': bool,
        'Azimuth brake 1 failure': bool,
        'Azimuth brake 2 failure': bool,
        'Azimuth breaker failure': bool,
        'Azimuth CAN bus amplifier 1 communication failure': bool,
        'Azimuth CAN bus amplifier 2 communication failure': bool,
        'Azimuth encoder failure': bool,
        'Azimuth tacho failure': bool,
        'Elevation servo failure': bool,
        'Elevation brake 1 failure': bool,
        'Elevation breaker failure': bool,
        'Elevation CAN bus amplifier 1 communication failure': bool,
        'Elevation encoder failure': bool,
        'Boresight servo failure': bool,
        'Boresight brake 1 failure': bool,
        'Boresight brake 2 failure': bool,
        'Boresight breaker failure': bool,
        'Boresight CAN bus amplifier 1 communication failure': bool,
        'Boresight CAN bus amplifier 2 communication failure': bool,
        'Boresight encoder failure': bool,
        'Boresight tacho failure': bool,
        'Azimuth computer disabled': bool,
        'Azimuth axis in stop': bool,
        'Azimuth brakes released': bool,
        'Azimuth stop at LCP': bool,
        'Azimuth power on': bool,
        'Azimuth AUX 1 mode selected': bool,
        'Azimuth AUX 2 mode selected': bool,
        'Azimuth immobile': bool,
        'Elevation computer disabled': bool,
        'Elevation axis in stop': bool,
        'Elevation brakes released': bool,
        'Elevation stop at LCP': bool,
        'Elevation power on': bool,
        'Elevation immobile': bool,
        'Boresight computer disabled': bool,
        'Boresight axis in stop': bool,
        'Boresight brakes released': bool,
        'Boresight stop at LCP': bool,
        'Boresight power on': bool,
        'Boresight AUX 1 mode selected': bool,
        'Boresight AUX 2 mode selected': bool,
        'Boresight immobile': bool,
        'Azimuth oscillation alarm': bool,
        'Elevation oscillation alarm': bool,
        'Boresight oscillation alarm': bool,
        'Azimuth commanded position': float,
        'Elevation commanded position':  float,
        'Boresight commanded position': float,
        'General summary fault': bool,
        'Power failure (latched)': bool,
        '24V power failure': bool,
        'General Breaker failure': bool,
        'Power failure (not latched)': bool,
        'Cabinet Overtemperature': bool,
        'Ambient temperature low (operation inhibited)': bool,
        'PLC-ACU interface error': bool,
        'ACU fan failure': bool,
        'Cabinet undertemperature': bool,
        'Time synchronisation error': bool,
        'ACU-PLC communication error': bool,
        'PCU operation': bool,
        'Safe': bool,
        'Lightning protection surge arresters': bool,
        'Co-Moving Shield off': bool,
        'ACU in remote mode': bool,
        'E-Stop servo drive cabinet': bool,
        'E-Stop service pole': bool,
        'E-Stop Az movable': bool,
        'Key Switch Bypass Emergency Limit': bool,
        'Day': int,
        'Time_UDP': float,
        'Corrected Azimuth': float,
        'Corrected Elevation': float,
        'Corrected Boresight': float,
        'Raw Azimuth': float,
        'Raw Elevation': float,
        'Raw Boresight': float,
        'Azimuth Current 1': float,
        'Azimuth Current 2': float,
        'Elevation Current 1': float,
        'Boresight Current 1': float,
        'Boresight Current 2': float,
        },
    'DataSets.StatusDetailed8100_3rd': {
        'Time': float,
        'Year': int,
        'Co-Rotator mode': str,
        'Co-Rotator commanded position': float,
        'Co-Rotator current position': float,
        'Co-Rotator computer disabled': bool,
        'Co-Rotator axis disabled': bool,
        'Co-Rotator axis in stop': bool,
        'Co-Rotator brakes released': bool,
        'Co-Rotator stop at LCP': bool,
        'Co-Rotator power on': bool,
        'Co-Rotator CCW limit: 2nd emergency': bool,
        'Co-Rotator CCW limit: emergency': bool,
        'Co-Rotator CCW limit: operating': bool,
        'Co-Rotator CCW limit: pre-limit': bool,
        'Co-Rotator CCW limit: operating (ACU software limit)': bool,
        'Co-Rotator CCW limit: pre-limit (ACU software limit)': bool,
        'Co-Rotator CW limit: pre-limit (ACU software limit)': bool,
        'Co-Rotator CW limit: operating (ACU software limit)': bool,
        'Co-Rotator CW limit: pre-limit': bool,
        'Co-Rotator CW limit: operating': bool,
        'Co-Rotator CW limit: emergency': bool,
        'Co-Rotator CW limit: 2nd emergency': bool,
        'Co-Rotator summary fault': bool,
        'Co-Rotator servo failure': bool,
        'Co-Rotator brake 1 failure': bool,
        'Co-Rotator breaker failure': bool,
        'Co-Rotator amplifier 1 failure': bool,
        'Co-Rotator motor 1 overtemperature': bool,
        'Co-Rotator overspeed': bool,
        'Co-Rotator amplifier power cycle interlock': bool,
        'Co-Rotator regeneration resistor 1 overtemperature': bool,
        'Co-Rotator CAN bus amplifier 1 communication failure': bool,
        'Co-Rotator encoder failure': bool,
        'Co-Rotator oscillation warning': bool,
        'Co-Rotator oscillation alarm': bool,
        'Co-Rotator immobile': bool,
        'Co-Rotator overcurrent motor 1': bool,
    },
    'test' : {
        'time' : float,
        'year' : int,
        'az mode' : str,
        'az axis error' : bool,
        'el mode' : str,
        'Qty of free program track stack positions' : int,
        }
    }
