devices:

    # Emulator on physical ACU at UCologne, with LAT software.
    'nanten-db-lat':
        # Address of the "remote" interface.
        'base_url': 'http://172.16.5.95:8100'
        # Address of the read-only "remote" interface.
        'readonly_url': 'http://172.16.5.95:8110'
        # Address of the "developer" interface.
        'dev_url': 'http://172.16.5.95:8080'
        # Local interface IP.
        'interface_ip': '172.16.5.10'

        # List of streams to configure.
        'streams':
            'main':
                'acu_name': 'PositionBroadcast'
                'port': 10000
                'schema': 'v3'
            'ext':
                'acu_name': 'PositionBroadcastExt'
                'port': 10001
                'active': False

        # For dataset description (see "datasets").
        'platform': 'ccat'

        # Motion limits (may differ from ACU limits).
        'motion_limits':
            'azimuth':
                'lower': -90.0
                'upper': 480.0
            'elevation':
                'lower': 20.0
                'upper': 90.0
            'boresight':
                'lower': 0.0
                'upper': 360.

    # Emulator on physical ACU at UCologne, with SATp software.
    'nanten-db-satp':
        # Address of the "remote" interface.
        'base_url': 'http://172.16.5.95:8100'
        # Address of the read-only "remote" interface.
        'readonly_url': 'http://172.16.5.95:8110'
        # Address of the "developer" interface.
        'dev_url': 'http://172.16.5.95:8080'
        # Local interface IP.
        'interface_ip': '172.16.5.10'

        # List of streams to configure.
        'streams':
            'main':
                'acu_name': 'PositionBroadcast'
                'port': 10000
                'schema': 'v2'
            'ext':
                'acu_name': 'PositionBroadcastExt'
                'port': 10001
                'active': False

        # For dataset description (see "datasets").
        'platform': 'satp'

        # Motion limits (may differ from ACU limits).
        'motion_limits':
            'azimuth':
                'lower': -90.0
                'upper': 480.0
            'elevation':
                'lower': 20.0
                'upper': 90.0
            'boresight':
                'lower': 0.0
                'upper': 360.

    # Software simulator ACU at UCologne.
    'simulator':
        # Address of the "remote" interface.
        'base_url': 'http://localhost:8102'
        # Address of the read-only "remote" interface.
        'readonly_url': 'http://localhost:8102'
        # Address of the "developer" interface.
        'dev_url': 'http://localhost:8102'
        # Local interface IP.
        'interface_ip': '172.16.5.10'

        # List of streams to configure.
        'streams':
            'main':
                'acu_name': 'PositionBroadcast'
                'port': 10008
                'schema': 'v2'
            'ext':
                'acu_name': 'PositionBroadcastExt'
                'port': 10009
                'active': False

        # For dataset description (see "datasets").
        'platform': 'satp'

        # Motion limits (may differ from ACU limits).
        'motion_limits':
            'azimuth':
                'lower': -90.0
                'upper': 480.0
            'elevation':
                'lower': 20.0
                'upper': 90.0
            'boresight':
                'lower': 0.0
                'upper': 360.


stream_schemas:
  v0:
    format: '<iddd'
    fields: ['Day', 'Time', 'Azimuth', 'Elevation']
  v1:
    format: '<iddddd'
    fields: ['Day', 'Time', 'Corrected_Azimuth', 'Corrected_Elevation', 'Raw_Azimuth', 'Raw_Elevation']
  v2:
    format: '<idddddddddddd'
    fields: ['Day', 'Time', 'Corrected_Azimuth', 'Corrected_Elevation', 'Corrected_Boresight', 'Raw_Azimuth', 'Raw_Elevation', 'Raw_Boresight', 'Azimuth_Current_1', 'Azimuth_Current_2', 'Elevation_Current_1', 'Boresight_Current_1', 'Boresight_Current_2']
  v3:
    format: '<iddddddddddd'
    fields: ['Day', 'Time', 'Corrected_Azimuth', 'Corrected_Elevation', 'Raw_Azimuth', 'Raw_Elevation', 'Azimuth_Current_1', 'Azimuth_Current_2', 'Azimuth_Current_3', 'Azimuth_Current_4', 'Elevation_Current_1', 'Elevation_Current_2']

datasets:
  ccat:
    'default_dataset': 'ccat'
    'third_axis_dataset': 'third_detail'
    'datasets':
      - ['ccat',       'DataSets.StatusCCatDetailed8100']
      - ['general',    'DataSets.StatusGeneral8100']
      - ['extra',      'DataSets.StatusExtra8100']
      - ['third',      'DataSets.Status3rdAxis']
      - ['third_detail', 'DataSets.StatusDetailed8100_3rd']
      - ['faults',     'DataSets.StatusDetailedFaults']
      - ['pointing',   'DataSets.CmdPointingCorrection']
      - ['spem',       'DataSets.CmdSPEMParameter']
      - ['weather',    'DataSets.CmdWeatherStation']
      - ['azimuth',    'Antenna.SkyAxes.Azimuth']
      - ['elevation',  'Antenna.SkyAxes.Elevation']
  satp:
    'default_dataset': 'satp'
    'datasets':
      - ['satp',       'DataSets.StatusSATPDetailed8100']
      - ['general',    'DataSets.StatusGeneral8100']
      - ['extra',      'DataSets.StatusExtra8100']
      - ['third',      'DataSets.Status3rdAxis']
      - ['faults',     'DataSets.StatusDetailedFaults']
      - ['pointing',   'DataSets.CmdPointingCorrection']
      - ['spem',       'DataSets.CmdSPEMParameter']
      - ['weather',    'DataSets.CmdWeatherStation']
      - ['azimuth',    'Antenna.SkyAxes.Azimuth']
      - ['elevation',  'Antenna.SkyAxes.Elevation']
