name: Test Sphinx Build

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - uses: actions/checkout@v2
  
    - name: Install soaculib
      run: |
        pip3 install -r requirements.txt
        pip3 install -r docs/requirements.txt
        pip3 install .
 
    - name: Sphinx Build
      uses: ammaraskar/sphinx-action@0.4
      with:
        docs-folder: "docs/"
        build-command: "make html"
